channels:
- defaults
- conda-forge
dependencies:
- python= 3.9
- eelbrain = 0.38
- mne = 1.5.0
- pip
- ipython
- jupyter
- ipywidgets
- jupytext
- seaborn
- requests
- joblib = 1.2
- matplotlib
- pingouin
- pandas
- numpy = 1.22.4